# Generated by Django 5.2.4 on 2025-08-14 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermonthlyusage',
            old_name='groups_joined',
            new_name='groups_created',
        ),
        migrations.RenameField(
            model_name='usermonthlyusage',
            old_name='sessions_joined',
            new_name='participations',
        ),
        # ✅ Ajout de year_month AVANT le AlterUniqueTogether
        migrations.AddField(
            model_name='usermonthlyusage',
            name='year_month',
            field=models.CharField(default='2025-08', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usermonthlyusage',
            unique_together={('user', 'year_month')},
        ),
        migrations.AddField(
            model_name='usermonthlyusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermonthlyusage',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='monthly_usage',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64, null=True)),
                ('plan', models.CharField(
                    choices=[('free', 'Free'), ('premium', 'Premium'), ('coach', 'Coach')],
                    default='free', max_length=16
                )),
                ('status', models.CharField(default='inactive', max_length=32)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='billing',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
        migrations.RemoveField(
            model_name='usermonthlyusage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='usermonthlyusage',
            name='year',
        ),
    ]
