# Generated by Django 5.2.4 on 2025-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_groups_joined_usermonthlyusage_groups_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonthlyusage',
            name='trainings_created',
            field=models.IntegerField(default=0),
        ),
    ]
