# Generated by Django 5.2.4 on 2025-08-11 13:17

import apps.users.managers.user_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_username_customuser_unique_username_ci'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.users.managers.user_manager.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
