# Generated by Django 5.2.4 on 2025-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_avatar_customuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('COACH', 'Coach')], default='FREE', max_length=16),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
