# Generated by Django 5.2.4 on 2025-08-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_plan_customuser_plan_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('user', 'User'), ('premium', 'Premium')], default='user', max_length=20),
        ),
    ]
