# Generated by Django 5.2.4 on 2025-08-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0002_alter_sportsession_options_and_more'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsession',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sports.sport'),
        ),
    ]
