# Generated by Django 5.2.4 on 2025-08-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0003_alter_sportsession_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsession',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude de l'emplacement.", null=True),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude de l'emplacement.", null=True),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='location',
            field=models.CharField(help_text='Lieu où se déroulera la session (adresse complète ou ville).', max_length=255),
        ),
    ]
