# Generated by Django 5.2.4 on 2025-08-10 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0004_sportsession_latitude_sportsession_longitude_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsession',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_sessions', to='teams.team'),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='event_type',
            field=models.CharField(choices=[('TRAINING', 'Entraînement'), ('FRIENDLY', 'Match amical'), ('COMPETITION', 'Compétition')], default='TRAINING', max_length=16),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='format',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('TEAM', 'Équipe unique'), ('VERSUS_1V1', '1 contre 1'), ('VERSUS_TEAM', 'Équipe contre équipe')], default='SOLO', max_length=16),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sessions', to='teams.team'),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Si activé, le coach doit approuver les demandes de participation.'),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='score_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='score_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('LOCKED', 'Verrouillé'), ('FINISHED', 'Terminé'), ('CANCELED', 'Annulé')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='max_players_per_team',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum de joueurs par équipe (si team_mode).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='min_players_per_team',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum de joueurs par équipe (si team_mode).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
