# Generated by Django 5.2.4 on 2025-08-10 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_remove_group_updated_at_and_more'),
        ('sport_sessions', '0005_sportsession_away_team_sportsession_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsession',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='groups.group'),
        ),
        migrations.AddField(
            model_name='sportsession',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Privée (coach uniquement)'), ('GROUP', 'Groupe (membres du groupe)'), ('PUBLIC', 'Publique (tout le monde)')], default='PRIVATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='creator',
            field=models.ForeignKey(help_text='Créateur', on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='is_public',
            field=models.BooleanField(default=True, help_text='⚠️ Hérité de visibility, ne pas modifier manuellement.'),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='max_players',
            field=models.PositiveIntegerField(default=10, help_text='Nombre total max.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='max_players_per_team',
            field=models.PositiveIntegerField(blank=True, help_text='Max par équipe.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='min_players_per_team',
            field=models.PositiveIntegerField(blank=True, help_text='Min par équipe.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Participants', related_name='joined_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sportsession',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Si activé, le coach doit approuver les demandes.'),
        ),
    ]
