# Generated by Django 5.2.4 on 2025-08-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0006_sportsession_group_sportsession_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExternalAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_attendees', to='sport_sessions.sportsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'last_name', 'first_name'], name='sport_sessi_session_50ed60_idx')],
                'unique_together': {('session', 'first_name', 'last_name')},
            },
        ),
    ]
