# Generated by Django 5.2.4 on 2025-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0008_sessionpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexternalattendee',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
