# Generated by Django 5.2.4 on 2025-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0009_sessionexternalattendee_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsession',
            name='event_type',
            field=models.CharField(choices=[('TRAINING', 'Entraînement'), ('FRIENDLY', 'Match amical'), ('COMPETITION', 'Compétition')], default='FRIENDLY', max_length=16),
        ),
    ]
