# Generated by Django 5.2.4 on 2025-08-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0010_alter_sportsession_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsession',
            name='is_public',
            field=models.BooleanField(default=False, help_text='⚠️ Hérité de visibility, ne pas modifier manuellement.'),
        ),
    ]
